/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Client = IDL.Record({
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'contactNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Visit = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'clientName' : IDL.Text,
  'user' : IDL.Principal,
  'visitDate' : Time,
  'longitude' : IDL.Float64,
  'notes' : IDL.Text,
  'contactNumber' : IDL.Text,
  'locationName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func([Client], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVisit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, Time, IDL.Text],
      [],
      [],
    ),
  'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getMyVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Client = IDL.Record({
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'contactNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Visit = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'clientName' : IDL.Text,
    'user' : IDL.Principal,
    'visitDate' : Time,
    'longitude' : IDL.Float64,
    'notes' : IDL.Text,
    'contactNumber' : IDL.Text,
    'locationName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func([Client], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVisit' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          Time,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getMyVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };