/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'name' : string,
  'notes' : string,
  'contactNumber' : string,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : bigint,
  'latitude' : number,
  'clientName' : string,
  'user' : Principal,
  'visitDate' : Time,
  'longitude' : number,
  'notes' : string,
  'contactNumber' : string,
  'locationName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[Client], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVisit' : ActorMethod<
    [string, string, string, number, number, Time, string],
    undefined
  >,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getMyVisits' : ActorMethod<[], Array<Visit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitsByUser' : ActorMethod<[Principal], Array<Visit>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];